### ISSUE TITLE
Replicas count missing when service is deployed globally

### ISSUE THREAD

**Issue by codref** [bhuisgen/zabbix-docker#1]
Let me say that this project rocks!  
I have a request though: I often use deploy global mode and I need to be alerted when a replica is down (i.e. when the number running of instances is != from the number of nodes eligible to the deploy).  
Do you think is something which can be easily implemented or worth implementing?

**Comment by codref** [comment]
Sorry for replying to my own issue, although a workaround is already addressed starting from Docker version  19.3 (https://github.com/docker/cli/pull/1410) which seems to allow a `max_replicas_per_node` constraint.  

This ticket can be closed, although the value, present on other monitoring tools, would indeed be useful also in here.

**Comment by bhuisgen** [comment]
Why not using the existing metrics about service tasks in running and total states ? I use that for zabbix agents as global service of course.
